### PR TITLE
correcting wrong words

### PR DESCRIPTION
**Pull request by jiacheo**
Correcting wrong words I 've left.

### CODE REVIEW

**Comment by kamol0001tk** [comment]
Thanks

**Comment by abhishek-anand** [comment]
@jiacheo I have added you with write access on the repository. If you get some time can you take a look at PRs originating for the Chinese versions e.g. https://github.com/FallibleInc/security-guide-for-developers/pull/33/files

**Comment by jiacheo** [comment]
Cool!! No problem! @abhishek-anand

**Comment by jiacheo** [comment]
Hi @abhishek-anand , I found that I don't have the write access on the repository, had you added that ?

**Comment by abhishek-anand** [comment]
@jiacheo Strange, it is showing your name (pending accept). Could you check and let me know if it shows up here https://github.com/FallibleInc/security-guide-for-developers/invitations

**Comment by jiacheo** [comment]
@abhishek-anand OK， now I have it .

**Pull request merged**
