### PR TITLE
Remove claim about MongoDB

### PR DESCRIPTION
**Pull request by Primigenus**
Unless you plan to explain why MongoDB sucks in the context of security, this statement does nothing to improve the document and instead just makes me suspect that the rest of the document includes similar claims with no backing. In which case, how am I to trust that this guide is dependable or trustworthy?

### CODE REVIEW

**Comment by yriveiro** [comment]
Mix feelings,

Indeed MongoDB is like a holy grail of pain ... But in this context, where we are talking about security, if the flaws are not documented is like a flame war discussion.

Guidelines about software to use that are reliable are welcome if are supported with arguments.

@Primigenus has a point ...

P.S: BTW MongoDB as any other thing that time series database is a shot in the dark, inconsistence, inconsistence everywhere.

**Comment by GloverDonovan** [comment]
Supporting this. As someone reading this guide, I want to know "why" MongoDB is considered bad. One sentence addressing the concerns with MongoDB security would be much more useful to readers than simply saying it "sucks".

**Comment by visualfanatic** [comment]
There are a few valid points in this "guide", but almost each one lacks an explanation.

**Comment by abhishek-anand** [comment]
@Primigenus Apologies, this indeed does not belong to security guide. I guess I was merely reflecting upon my experience using Mongo, but that does not belong here. I have merged your PR. Thanks!
@visualfanatic We would be adding content gradually which which explain most of the items and then we will revisit the checklist at the end (as mentioned in the contents).

**Pull request merged**
